---
- hosts: jenkins-slave
  become: true
  tasks:
    - name: Update Ubuntu repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install Java
      apt:
        name: openjdk-11-jre   # change to 17 if needed
        state: present

    - name: Download Maven package
      get_url:
        url: https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
        dest: /opt/apache-maven-3.9.2-bin.tar.gz
        mode: '0644'

    - name: Extract Maven package
      unarchive:
        src: /opt/apache-maven-3.9.2-bin.tar.gz
        dest: /opt/
        remote_src: yes

    - name: Create Maven environment file
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export M2_HOME=/opt/apache-maven-3.9.2
          export PATH=$M2_HOME/bin:$PATH
        mode: '0755'

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add Jenkins user to docker group
      user:
        name: jenkins
        groups: docker
        append: yes
